### ISSUE TITLE
synths.lib documentation

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faustlibraries#1]
**synths.lib
This library contains a collection of envelope generators. Its official prefix is sy.**

==> this seem like a documentation error, no ? @rmichon

**Comment by rmichon** [comment]
Indeed, just fixed this in 165f7c6e28d7740145d19623c2c25342249d5459. By the way I made some modifications to the way the `generateDoc` script works for it to be compatible with the latest version of `pandoc`. These updates also ensure that `generateDoc` relies less on `sed` which is a good thing. I also made a tiny modification to `faust2md` (7dc7788c8b120c729e7542195d851a304f99e948) which is only compatible with `python2` to ensure that it uses this version of python for execution...
