### ISSUE TITLE
Missing prefix ma. in PI and SR in notchw

### ISSUE THREAD

**Issue by jdsierral** [grame-cncm/faustlibraries#10]
Hey I hope Im not bothering too much lately, but it seems like the symbols for PI and SR are missing the `ma.` prefix in the `filters.lib` library in the `notchw` filter. 

https://github.com/grame-cncm/faustlibraries/blob/9c5c1524be6ed96780db6b6cfa1851dd5ce29cba/filters.lib#L496-L500

I hope this helps

JuanS

**Comment by sletz** [comment]
Thanks. Fixed in https://github.com/grame-cncm/faustlibraries/commit/26d4145859b4a603ddfc78785dc2442be504fd3b.
