### ISSUE TITLE
Error in moogLadder filter algorithm

### ISSUE THREAD

**Issue by Cioppa90** [grame-cncm/faustlibraries#104]
Hi, I was playing with the moogLadder filter and I noticed a strange behaviour. Even if the resonance is high (near 25), if the cutoff frequency is high as well (around 10000Hz) the resonance completely disappears. Furthermore, it seems that the maximum cutoff frequency is indeed around 12000Hz, and not the sampling frequency as it shold be. I tried to get to the source code but I wasn's able to. However, I looked in the documentation and I saw that it is essentially Will Pirkle's implementation, so I re-implemented it and and found out that it has several issues that render it essentially unstable at high cutoff frequencies. The first issue is that, to compute the memory state necessary for the zdf prediction step, Pirkle uses the warped cutoff frequency g, where it should have used g/(1 + g). The second issue is that the memories used for the feedback updating are taken as the memories s of the one pole filters, while they should be (1 - g/(1 + g))*s instead. I implemented such corrections and the resulting filter is very stable. If you want I could provide a MatLab or C++ code.

If you need any further informations, please feel free to reach me at dellacioppa.lorenzo @ gmail.com

cheers

Lorenzo

**Comment by Cioppa90** [comment]
Yeah, he is a friend of mine, I just didn't know he was already on this, my bad!

**Comment by sletz** [comment]
Done in https://github.com/grame-cncm/faustlibraries/commit/4748e34a58d1fb8c07afeca570790820c9787243
