### ISSUE TITLE
Add links to source code from libraries docs pages

### ISSUE THREAD

**Issue by dxinteractive** [grame-cncm/faustlibraries#109]
I would love to see some links going from library pages (e.g. https://faustlibraries.grame.fr/libs/oscillators/) to their corresponding code (e.g. https://github.com/grame-cncm/faustlibraries/blob/master/oscillators.lib).

I often find what I'd like to use in the docs, and then would like to see the source to see how they are implemented to guess their efficiency.

Also I often then try to find a link to https://github.com/grame-cncm/faustlibraries from the faustlibraries docs site but I've not been able to find one on the homepage or any of the subpages. I usually end up typing "faustlibraries github" into google. Perhaps I've missed it, but if there isn't one it'd be great to have one added to https://faustlibraries.grame.fr/. Thanks.

**Comment by sletz** [comment]
Done, link to source file added in the _References_ section on the header of each library, something like:

**References**
https://github.com/grame-cncm/faustlibraries/blob/master/analyzers.lib

**Comment by dxinteractive** [comment]
Wonderful, thanks for your super fast work!
