### ISSUE TITLE
compilation of Max 8 externals for Apple ARM64 -> ok

### ISSUE THREAD

**Issue by opasquetdotfr** [grame-cncm/faustlibraries#174]
Hello!

Three, or four, details for Mac users willing to build externals for Max (8.5.7 for instance):

— https://faustide.grame.fr does not work for Apple ARM64 (Ventura 13.6.3).

— "faust2max6 -universal" does WORK for Apple ARM64 (Ventura 13.6.3).

— If you get the following error:
`Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`
install "pkg-config" using macport for instance:
`port install pkg-config`

— "$MAXSDK" within the "faustpath" file should target the fully downloaded Max SDK 8.2 like this:
`".../max-sdk/source/max-sdk-base/c74support"`
Only header and lib files on the folder "c74support" are needed.

**Comment by sletz** [comment]
Thanks. I see your Faust related work [here](https://www.opasquet.fr/gen-faust-max-externals/). Is the Faust DSP code available ? Would you be interested to be listed on the [Powered By Faust](https://faust.grame.fr/community/powered-by-faust/) page ?
