### ISSUE TITLE
Update of hoa.lib

### ISSUE THREAD

**Issue by wargreen** [grame-cncm/faustlibraries#18]
Hello,
I've update hoa.lib with the 3D function present in the original source folder.
The forked project is here https://framagit.org/wargreen/hoalibrary-faust

Do you prefere a PR or update it yourself ?
Thank you

**Comment by sletz** [comment]
Yes a PR would be great thanks !

**Comment by sletz** [comment]
But please update the additional libraries you're using, and document each function following what is explained here: https://github.com/grame-cncm/faustlibraries. Thanks !
