### ISSUE TITLE
Faust audio error

### ISSUE THREAD

**Issue by yellowpepero** [grame-cncm/faustlibraries#190]
music=library("music.lib");
oscil=library("oscillator.lib");

carrier=nentry("Original Wave", 0, 0, 2, 1)
        : select3(_, music.osc(2000), oscil.sawtooth(2000), oscil.square(2000));
modulator=music.osc(200) ;
gate=button("start!");

process=carrier <: _ * (1 - gate), _ * modulator * gate :> _;

until here is my codes, but I got 

oscillator.lib : 136 : ERROR : undefined symbol : ma

this Error.. How can I solve it ? 
Thank you

**Comment by sletz** [comment]
Better use stdfaust.lib, see https://faustlibraries.grame.fr
