### ISSUE TITLE
License of maxmsp.lib RBJ filters

### ISSUE THREAD

**Issue by jpcima** [grame-cncm/faustlibraries#23]
Hello,

I have an application that requires me to use the RBJ filter set, which is available in the library `maxmsp.lib`.
A I have observed, this library seems a bit dated, it's not in `stdfaust.lib`, but also it's licensed as ordinary LGPL without exception.

Currently, I wish to include this in a BSD-licensed project, preferably without submitting the whole program to constraints of LGPL.

The option is to reimplement this myself, but it's a shame to remake a library of such common, documented, easily implemented filters.

Would it be possible to revise the license of RBJ filters?
I would like to ask original authors, however they are not mentioned in the file source, and git history does not go far enough to know this information.

Thank you

**Comment by sletz** [comment]
Seems feasible yes, @orlarey do you see any reason not to do it ?

**Comment by sletz** [comment]
Licence update done in https://github.com/grame-cncm/faustlibraries/commit/6e334524e663a6faac4de324d66ec796e35d9bdf

**Comment by jpcima** [comment]
Thank you ! very appreciated.
Should the license metadata not be updated as well ?

For example in `envelopes.lib`, this is written:
`declare license "LGPL with exception";`

**Comment by sletz** [comment]
Done in https://github.com/grame-cncm/faustlibraries/commit/e82f494447fc28d09a62d572a794c3cadaebd769

**Comment by jpcima** [comment]
Thanks, closing
