### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by Reaper10** [grame-cncm/faustlibraries#49]
I want to help by making a piano, epiano, harpsichord and Celesta body resonator for faust. I know about mesh2faust and svg. Can you help me with learn how to do this? Could you walk me through what I need to do?

**Comment by sletz** [comment]
Using the GitHub issue is not the best way to get help.

I suggest you come on the Faust Slack channel here: https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g our the Faust Audio Programmer discord with a #faust channel (https://theaudioprogrammer.com/community/).
