### ISSUE TITLE
SampleRate limit is too low

### ISSUE THREAD

**Issue by iBundin** [grame-cncm/faustlibraries#5]
70. `SR 			= min(192000.0, max(1.0, fconstant(int fSamplingFreq, <math.h>)));`

192000 is not enough for all use cases. Sometimes, there is a need to use 352800 hz (dxd format).
I've managed to deal with this issue inside my Faust program though by using the code below:

`mySR = min(352800, max(1.0, fconstant(int fSamplingFreq, <math.h>)));`

**Comment by rmichon** [comment]
@orlarey what do you think about that? I think this change should be made, I can take care of it.

**Comment by orlarey** [comment]
We can't do that. This would double the size of all delay lines. @iBundin The best option is to have a private version of maths.lib in which the definition of SR is modified.

**Comment by rmichon** [comment]
+1
