### ISSUE TITLE
oscillators.lib : 488 : ERROR : syntax error, unexpected IDENT

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faustlibraries#53]
I'm getting a lot of patch that do not compile because of that error - a simple sineSynth example reproduces the issue

```
// tosc.dsp - test simple oscillator + MIDI bindings
import("stdfaust.lib");
process = g * a * os.oscrs(f*b) <: _,_;
a = hslider("gain [midi:ctrl 7]",1,0,1,0.001);
f = hslider("freq",392.0,200.0,450.0,0.01);
b = ba.semi2ratio(hslider("bend [midi:pitchwheel]",0,-2,2,0.001));
g = button("gate");
```

thanks !

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faustlibraries/commit/12883342d0fc7da7d0e652293ebf3956df2c77d5.

**Comment by magnetophon** [comment]
@sletz Thanks! Sorry for the sloppy PR, not sure how that happened!

**Comment by sletz** [comment]
The thing is that we (GRAME) should have a more robust way to check PR before merging them, do you agree @rmichon ?

**Comment by jcelerier** [comment]
it could be worth adding a small CI script that tries to compile the various examples on the faust website with the current faustlibraries maybe to have a first-line automatic check

**Comment by jcelerier** [comment]
thanks @sletz for the fast fix !

**Comment by rmichon** [comment]
I couldn't agree more. We've been talking about putting together a system that would take all the functions of all the libraries and automatically generate examples from them that could also be used as tests.
