### ISSUE TITLE
Make the behaviour of si.smoo SR-independent.

### ISSUE THREAD

**Issue by dariosanfilippo** [grame-cncm/faustlibraries#67]
@josmithiii 

Hi, Julius and all. Not an issue but just an idea to make the behaviour of si.smoo more consistent.

Instead of a fixed value for the pole, we could have:

smoo = si.smooth(1 - (44.1 / ma.SR));

The value above would preserve the current .999 coefficient for the default SR.

Best,
Dario

**Comment by sletz** [comment]
This seems like a good idea: @josmithiii ? @rmichon  ? @orlarey ?

**Comment by rmichon** [comment]
I think that's a great idea! Wanna do a pull request for this?

Cheers,

Romain

**Comment by dariosanfilippo** [comment]
Sure, I just did it.

Cheers,
Dario
